Update

diff --git a/.github/workflows/check-lfs-pointers.yml b/.github/workflows/check-lfs-pointers.yml
--- a/.github/workflows/check-lfs-pointers.yml
+++ b/.github/workflows/check-lfs-pointers.yml
@@ -1,4 +1,4 @@
-name: Check Git LFS
+name: Check Git LFS Pointers
 
 on:
   pull_request_target:
@@ -15,14 +15,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
-          lfs: false
+          ref: ${{ github.head_ref }}
 
       - name: Check for LFS pointer issues
         run: |
           git lfs fsck
-          if [ $? -ne 0 ]; then
-            echo "::error::Found issues with Git LFS pointers"
-            exit 1
+          status=$?
+          if [ $status -ne 0 ]; then
+            echo "::error::Install Git LFS and fix the files with 'git lfs migrate import --no-rewrite <path to the files>'"
           fi
+          exit $status
